[[news]]
title = "ðŸ”’ Mastering Data Privacy: Join the ASSURED Workshop at IDCC 2026"
anews = '''

Registration is now OPEN for our essential workshop at the International Data Curation Conference (IDCC) 2026!
The ASSURED Project is developing an accreditation scheme for handling sensitive research data. This workshop is your opportunity to gain critical expertise.

What You Will Learn:
â€¢ Safe Outputs: Explore the issues emerging from sensitive data results and learn the principles for producing non-disclosive, safe outputs.
â€¢ Key Techniques: Focus on methods like Statistical Disclosure Control (SDC) to minimise harm and protect privacy.
â€¢ Interactive Training: This is a highly interactive-focused session, encouraging rich discussion among researchers and data professionals.

Who Should Attend?
This training is important for:
â€¢ Researchers working with sensitive data.
â€¢ Data Curators and professionals involved in data access.
â€¢ Anyone responsible for ethical data release.

Elevate your professional standards. Secure your spot and become more confident in working with sensitive data.

ðŸ‘‰ Register Today for the Workshop at IDCC 2026: https://t1p.de/8ltfu



'''
date = " "
by = "Assured Training"
pin = "true"
originalurl = "https://www.linkedin.com/posts/assured-training_datagovernance-openscience-researchjobs-activity-7386340308332171266-quuP?utm_source=share&utm_medium=member_desktop&rcm=ACoAADxrZGwB5ESC6hEubnIuDfWq1FtzkujA134"
source = "linkedin"


[[news]]
title = "We're hiring a Research Associate!ðŸš€"
anews = '''
Learn more and apply here: https://lnkd.in/ejpuSYnv

Are you passionate about the intersection of FAIR data, open science, and researcher education? Join the Data Services for the Social Sciences department, where you'll play a vital role in ensuring safe, reproducible research.

This role is centered on our GESIS Secure Data Center and the exciting, multi-partner ASSURED project. You will be key in developing a new Safe Researcher Training program both in Germany and internationally.

Your Impact Will Include:

â€¢ Lead the coordination and communication for the multi-consortium ASSURED project.

â€¢ Design and continuously improve digital learning materials (video tutorials, interactive exercises) in spatial transcriptomics data processing.

â€¢ Contribute to high-impact research activities on data governance, privacy, and secure data infrastructures.

â€¢ Provide essential support for the Secure Data Center, including conducting statistical disclosure reviews.


What We Are Looking For:

â€¢ A completed Masterâ€™s degree and a completed or in-progress Ph.D. ðŸŽ“

â€¢ Proven experience working in Trusted Research Environments (TREs) or with sensitive data.

â€¢ Strong command of quantitative methods and statistical programs like Python, R, and Stata.


We offer an international, interdisciplinary environment with flexible working hours, mobile working options, and excellent benefits, including subsidies for childcare.

Ready to shape the future of secure social science research?

Learn more and apply here: https://lnkd.in/ejpuSYnv
'''
date = " "
by = "Assured Training"
pin = "true"
originalurl = "https://www.linkedin.com/posts/assured-training_datagovernance-openscience-researchjobs-activity-7386340308332171266-quuP?utm_source=share&utm_medium=member_desktop&rcm=ACoAADxrZGwB5ESC6hEubnIuDfWq1FtzkujA134"
source = "linkedin"


[[news]]
title = "We are recruiting!"
anews = "We are currently looking for someone to join the ASSURED team for 3 years to develop and deliver training to researchers and data professionals working with sensitive data. We're an international team, spread across multiple sites, although this role sits within the Secure Data Center at GESIS Cologne. If you want to work in a small but dynamic team and play your part in the exciting development work here at ASSURED and GESIS, then please get in touch!"
date = " "
by = "Assured Training"
pin = "true"
originalurl = "https://www.linkedin.com/posts/assured-training_research-associate-in-trusted-research-environments-activity-7386091411781238784-AKdM?utm_source=share&utm_medium=member_desktop&rcm=ACoAADxrZGwB5ESC6hEubnIuDfWq1FtzkujA134"
source = "linkedin"

[[news]]
title = "The ASSURED team had an amazing time at the #EOSCSymposium2024 in Berlin! We spent three days discus"
anews = "The ASSURED team had an amazing time at the #EOSCSymposium2024 in Berlin! We spent three days discussing FAIR sensitive data and training opportunities. Presenting our poster was a highlight. LetÂ´s foster FAIRness and trust in research and researchers. #OpenScience #FAIRData #SensitiveData #SafeP..."
date = "2025-08-18"
by = "Assured Training"
pin = "true"
originalurl = "https://www.linkedin.com/feed/update/urn:li:activity:7255138012093628416"
source = "linkedin"
